# -*- coding: utf-8 -*-

from ..vendor import Qt
from ..vendor.Qt import QtCore, QtWidgets, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 728)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_option = QtWidgets.QPushButton(Form)
        self.btn_option.setObjectName("btn_option")
        self.horizontalLayout_3.addWidget(self.btn_option)
        self.btn_currentproj = QtWidgets.QPushButton(Form)
        self.btn_currentproj.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_currentproj.setObjectName("btn_currentproj")
        self.horizontalLayout_3.addWidget(self.btn_currentproj)
        self.btn_return = QtWidgets.QPushButton(Form)
        self.btn_return.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_return.setObjectName("btn_return")
        self.horizontalLayout_3.addWidget(self.btn_return)
        self.btn_moveon = QtWidgets.QPushButton(Form)
        self.btn_moveon.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_moveon.setObjectName("btn_moveon")
        self.horizontalLayout_3.addWidget(self.btn_moveon)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.view_directory = QtWidgets.QTreeView(Form)
        self.view_directory.setSizeIncrement(QtCore.QSize(0, 0))
        self.view_directory.setBaseSize(QtCore.QSize(0, 0))
        self.view_directory.setObjectName("view_directory")
        self.view_directory.header().setVisible(False)
        self.horizontalLayout_2.addWidget(self.view_directory)
        self.view_file = QtWidgets.QTreeView(Form)
        self.view_file.setObjectName("view_file")
        self.horizontalLayout_2.addWidget(self.view_file)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_filepath = QtWidgets.QLineEdit(Form)
        self.line_filepath.setObjectName("line_filepath")
        self.verticalLayout.addWidget(self.line_filepath)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_filter = QtWidgets.QLabel(Form)
        self.label_filter.setObjectName("label_filter")
        self.horizontalLayout.addWidget(self.label_filter)
        self.line_filter = QtWidgets.QLineEdit(Form)
        self.line_filter.setObjectName("line_filter")
        self.horizontalLayout.addWidget(self.line_filter)
        self.label_type = QtWidgets.QLabel(Form)
        self.label_type.setObjectName("label_type")
        self.horizontalLayout.addWidget(self.label_type)
        self.combo_type = QtWidgets.QComboBox(Form)
        self.combo_type.setEnabled(True)
        self.combo_type.setMinimumSize(QtCore.QSize(200, 0))
        self.combo_type.setObjectName("combo_type")
        self.horizontalLayout.addWidget(self.combo_type)
        self.chkbox_setproject = QtWidgets.QCheckBox(Form)
        self.chkbox_setproject.setChecked(True)
        self.chkbox_setproject.setObjectName("chkbox_setproject")
        self.horizontalLayout.addWidget(self.chkbox_setproject)
        self.btn_open = QtWidgets.QPushButton(Form)
        self.btn_open.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_open.setObjectName("btn_open")
        self.horizontalLayout.addWidget(self.btn_open)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tab = QtWidgets.QTabWidget(Form)
        self.tab.setObjectName("tab")
        self.tab_bookmark = QtWidgets.QWidget()
        self.tab_bookmark.setObjectName("tab_bookmark")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_bookmark)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.view_bookmark = QtWidgets.QTreeView(self.tab_bookmark)
        self.view_bookmark.setObjectName("view_bookmark")
        self.gridLayout_2.addWidget(self.view_bookmark, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radio_bookmark_directory = QtWidgets.QRadioButton(self.tab_bookmark)
        self.radio_bookmark_directory.setChecked(True)
        self.radio_bookmark_directory.setObjectName("radio_bookmark_directory")
        self.horizontalLayout_5.addWidget(self.radio_bookmark_directory)
        self.radio_bookmark_file = QtWidgets.QRadioButton(self.tab_bookmark)
        self.radio_bookmark_file.setObjectName("radio_bookmark_file")
        self.horizontalLayout_5.addWidget(self.radio_bookmark_file)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.tab.addTab(self.tab_bookmark, "")
        self.tab_history = QtWidgets.QWidget()
        self.tab_history.setObjectName("tab_history")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_history)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radio_history_project = QtWidgets.QRadioButton(self.tab_history)
        self.radio_history_project.setObjectName("radio_history_project")
        self.horizontalLayout_4.addWidget(self.radio_history_project)
        self.radio_history_file = QtWidgets.QRadioButton(self.tab_history)
        self.radio_history_file.setChecked(True)
        self.radio_history_file.setObjectName("radio_history_file")
        self.horizontalLayout_4.addWidget(self.radio_history_file)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.view_history = QtWidgets.QTreeView(self.tab_history)
        self.view_history.setObjectName("view_history")
        self.gridLayout_3.addWidget(self.view_history, 1, 0, 1, 1)
        self.tab.addTab(self.tab_history, "")
        self.verticalLayout.addWidget(self.tab)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(4, 1)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(Qt.QtCompat.translate("Form", "Form", None, -1))
        self.btn_option.setText(Qt.QtCompat.translate("Form", "Option", None, -1))
        self.btn_currentproj.setText(Qt.QtCompat.translate("Form", "CurrentProject", None, -1))
        self.btn_return.setText(Qt.QtCompat.translate("Form", "<<", None, -1))
        self.btn_moveon.setText(Qt.QtCompat.translate("Form", ">>", None, -1))
        self.label_filter.setText(Qt.QtCompat.translate("Form", "   NameFilter:", None, -1))
        self.label_type.setText(Qt.QtCompat.translate("Form", " ExtensionType:", None, -1))
        self.chkbox_setproject.setText(Qt.QtCompat.translate("Form", "SetProject", None, -1))
        self.btn_open.setText(Qt.QtCompat.translate("Form", "Open", None, -1))
        self.radio_bookmark_directory.setText(Qt.QtCompat.translate("Form", "Directory", None, -1))
        self.radio_bookmark_file.setText(Qt.QtCompat.translate("Form", "File", None, -1))
        self.tab.setTabText(self.tab.indexOf(self.tab_bookmark), Qt.QtCompat.translate("Form", "Bookmark", None, -1))
        self.radio_history_project.setText(Qt.QtCompat.translate("Form", "Project", None, -1))
        self.radio_history_file.setText(Qt.QtCompat.translate("Form", "File", None, -1))
        self.tab.setTabText(self.tab.indexOf(self.tab_history), Qt.QtCompat.translate("Form", "History", None, -1))

